# TLE_09 Icons 
# Base on Nuvola vector icon theme
# (c) 2002-2003 David Vignoni <dvgn@libero.it>
[Icon Theme]
Name=TLE_09
Name[th]=ลินุกซ์ทะเล_๙
Comment=Vector Theme
Comment[th]=ลินุกซ์ทะเล_๙ โดยปริยาย
Inherits=hicolor,Human,Tango,gnome
Directories=scalable/actions,scalable/apps,scalable/filesystems,scalable/mimetypes,scalable/emblems,scalable/devices,scalable/stock
#Example=gnome-main-menu
Example=gnome-theme-preview.svg

[scalable/actions]
MinSize=1
Size=48
MaxSize=256
Context=Actions
Type=scalable

[scalable/apps]
MinSize=1
Size=48
MaxSize=256
Context=Applications
Type=scalable

[scalable/devices]
MinSize=1
Size=48
MaxSize=256
Context=Devices
Type=scalable

[scalable/emblems]
#this is a bug 102677, should be 24
Size=48
Context=Emblems
Type=Scalable

[scalable/filesystems]
MinSize=1
Size=48
MaxSize=128
Context=FileSystems
Type=Scalable

[scalable/mimetypes]
MinSize=1
Size=48
MaxSize=128
Context=MimeTypes
Type=Scalable

[scalable/stock]
MinSize=1
Size=48
MaxSize=128
Context=Stock
Type=Scalable

